;this file for FamiTone2 library generated by text2data tool
.export _music_data
_music_data:
	.byte 6
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	; v160 ROM save: old stock gameplay song is no longer used.
	; Gameplay uses music_data_main, so song slot 1 safely points to silence.
	.word @song0ch4,@song0ch4,@song0ch4,@song0ch4,@song0ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env11
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env6,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env3,@env6,@env10
	.byte $00
	.byte $30 ;instrument $04
	.word @env1,@env7,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env3,@env8,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env3,@env8,@env10
	.byte $00
	.byte $30 ;instrument $08
	.word @env5,@env9,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c7,$c5,$c4,$c3,$c3,$c2,$06,$c1,$0a,$c0,$00,$09
@env3:
	.byte $c6,$c6,$c5,$c4,$c3,$09,$c2,$08,$c1,$0f,$c0,$00,$0a
@env4:
	.byte $c8,$c3,$c2,$c1,$02,$c0,$00,$05
@env5:
	.byte $c5,$c5,$c4,$c4,$c3,$c0,$00,$05
@env6:
	.byte $c0,$c0,$c5,$c5,$c7,$c7,$00,$00
@env7:
	.byte $c6,$c3,$c0,$00,$02
@env8:
	.byte $c0,$02,$c4,$02,$c7,$c7,$c7,$00,$00
@env9:
	.byte $c6,$c6,$c0,$00,$02
@env10:
	.byte $c4,$00,$00
@env11:
	.byte $c0,$0b,$c1,$c2,$c3,$c4,$c3,$c2,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $8c,$33,$33,$36,$95
@song0ch0loop:
@ref1:
	.byte $9f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref2:
	.byte $8e,$33,$33,$36,$95
@song0ch1loop:
@ref3:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref4:
	.byte $80,$33,$33,$90,$32,$80,$36,$83,$00,$8d
@song0ch2loop:
@ref5:
	.byte $9f
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref6:
	.byte $8a,$1f,$1f,$90,$17,$82,$1e,$91
@song0ch3loop:
@ref7:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref8:
	.byte $9f
@song0ch4loop:
@ref9:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


; v160: Removed unused original song 1 data to free PRG ROM.
; MUSIC_GAME is not used by game.c anymore; real gameplay music is music_data_main.


@song2ch0:
	.byte $fb,$03
@ref50:
	.byte $84,$3d,$3d,$3c,$85,$3d,$3d,$40,$a5
@song2ch0loop:
@ref51:
	.byte $bf
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref52:
	.byte $86,$3d,$3d,$3c,$85,$3d,$3d,$40,$a5
@song2ch1loop:
@ref53:
	.byte $bf
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref54:
	.byte $80,$3c,$00,$3c,$00,$3c,$00,$83,$3c,$00,$3c,$00,$88,$40,$8f,$00
	.byte $93
@song2ch2loop:
@ref55:
	.byte $bf
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref56:
	.byte $8a,$1f,$1f,$82,$1e,$85,$8a,$1f,$1f,$90,$17,$82,$1e,$a1
@song2ch3loop:
@ref57:
	.byte $bf
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref58:
	.byte $bf
@song2ch4loop:
@ref59:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@ref60:
	.byte $84,$24,$24,$83,$22,$22,$83,$20,$20,$83,$1f,$1a,$89,$32,$95
@song3ch0loop:
@ref61:
	.byte $bf
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref62:
	.byte $86,$24,$24,$83,$22,$22,$83,$20,$20,$83,$1f,$1a,$89,$32,$85,$32
	.byte $8d
@song3ch1loop:
@ref63:
	.byte $bf
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref64:
	.byte $80,$25,$01,$23,$01,$21,$01,$1f,$1a,$85,$01,$88,$32,$89,$00,$89
@song3ch2loop:
@ref65:
	.byte $bf
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref66:
	.byte $82,$1f,$8a,$1f,$82,$1d,$8a,$1f,$82,$1b,$8a,$1f,$82,$1b,$18,$89
	.byte $90,$17,$82,$1e,$91
@song3ch3loop:
@ref67:
	.byte $bf
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref68:
	.byte $bf
@song3ch4loop:
@ref69:
	.byte $bf
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$04
@song4ch0loop:
@ref70:
	.byte $84,$28,$8d,$8c,$40,$89,$40,$89,$40,$8d,$84,$28,$85
@ref71:
	.byte $24,$8d,$8c,$3c,$89,$3c,$89,$3c,$8d,$84,$24,$85
@ref72:
	.byte $28,$8d,$8c,$40,$89,$40,$89,$40,$8d,$84,$28,$85
@ref73:
	.byte $1a,$8d,$8c,$32,$89,$36,$89,$36,$95
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref74:
	.byte $86,$28,$8d,$8e,$40,$89,$40,$89,$40,$8d,$86,$28,$85
@ref75:
	.byte $24,$8d,$8e,$3c,$89,$3c,$89,$3c,$8d,$86,$24,$85
@ref76:
	.byte $28,$8d,$8e,$40,$89,$40,$89,$40,$8d,$86,$28,$85
@ref77:
	.byte $1a,$8d,$8e,$32,$89,$36,$89,$36,$95
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref78:
	.byte $80,$28,$87,$00,$26,$00,$88,$29,$00,$85,$80,$29,$01,$29,$01,$26
	.byte $00,$88,$29,$01,$80,$29,$22,$81
@ref79:
	.byte $24,$87,$00,$22,$00,$88,$25,$00,$85,$80,$25,$01,$25,$01,$22,$00
	.byte $25,$01,$25,$22,$81
@ref80:
	.byte $28,$87,$00,$26,$00,$88,$29,$00,$85,$80,$29,$01,$29,$01,$26,$00
	.byte $88,$29,$01,$80,$29,$00,$81
@ref81:
	.byte $32,$87,$00,$30,$00,$33,$00,$85,$37,$01,$37,$01,$34,$00,$88,$37
	.byte $01,$1f,$1e,$81
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref82:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$17,$8a,$1f,$1f,$1f,$82,$1f,$8a
	.byte $1f,$1f,$1f,$90,$17,$8a,$1f,$82,$1e,$85
	.byte $ff,$10
	.word @ref82
	.byte $ff,$10
	.word @ref82
@ref85:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$17,$8a,$1f,$1f,$1f,$82,$1f,$8a
	.byte $1f,$1f,$1f,$90,$16,$85,$17,$16,$81
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$03
@ref90:
	.byte $84,$32,$8d,$2c,$85,$28,$a5
@song5ch0loop:
@ref91:
	.byte $bf
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@ref92:
	.byte $86,$32,$8d,$2c,$85,$28,$a5
@song5ch1loop:
@ref93:
	.byte $bf
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@ref94:
	.byte $88,$32,$85,$00,$85,$80,$2c,$85,$88,$2a,$95,$00,$8d
@song5ch2loop:
@ref95:
	.byte $bf
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@ref96:
	.byte $90,$16,$85,$8a,$1f,$1f,$1e,$85,$90,$16,$a5
@song5ch3loop:
@ref97:
	.byte $bf
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@ref98:
	.byte $bf
@song5ch4loop:
@ref99:
	.byte $bf
	.byte $fd
	.word @song5ch4loop

; ---------------------------------------------------------------------------

; ---------------------------------------------------------------------------
; v98 restored title intro song from uploaded intro(1).s
; Separate one-song FamiTone2 data set named music_data_untitled.
; Title screen initializes this and plays song 0.
; ---------------------------------------------------------------------------

; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_untitled:=music_data_untitled

music_data_untitled:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_untitled

@instruments:
	.byte $30 ; 00 : Electric Guitar (clean)
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $a9, $80, $22, $83, $2a, $85, $34, $42, $b3, $22, $b5, $42, $99, $44, $99, $42
@song0ref20:
	.byte $a7, $20, $83, $2e, $85, $34, $40, $b3, $20, $b5, $40, $ed, $26, $b5, $44, $99, $48, $99, $00, $99, $48, $b5, $44, $99
	.byte $42, $b5, $1c, $b5, $42, $b5, $1c
	.byte $ff, $0b
	.word @song0ref20
@song0ref54:
	.byte $b5, $20, $b5, $38, $b5, $20, $b5, $40, $b5, $20, $b5, $2a, $b5, $38, $b5, $4a, $b5, $38
@song0ref72:
	.byte $b5, $4a, $99, $4c, $99, $00, $8b, $50, $a7, $50, $b5, $1c, $b5, $22, $ed, $42, $b5, $22, $b5, $20, $ed, $40, $b5, $20
	.byte $b5, $26, $ed, $44, $ed, $1c, $ed, $42, $b5, $34, $b5, $20, $ed, $40
	.byte $ff, $11
	.word @song0ref54
	.byte $42
	.byte $ff, $26
	.word @song0ref72
	.byte $ff, $11
	.word @song0ref54
	.byte $42
	.byte $ff, $0d
	.word @song0ref72
	.byte $42, $4c, $5a, $b1, $3a, $b5, $5a, $99, $5c, $99, $5a, $b5, $46, $50, $58, $b1, $38, $b5, $58, $ed, $3e, $b5, $56, $99
	.byte $5a, $99, $5a, $8b, $5c, $8b, $60, $b5, $56, $99, $5a, $b5, $3a, $b5, $5a, $b5, $3a, $b5, $38, $46, $50, $58, $af, $38
	.byte $b5, $58, $b5, $38, $b5, $50, $b5, $38, $b5, $58, $b5, $38, $b5, $52, $b5, $42, $b5, $50, $b5, $42, $b5, $5a, $f9, $e3
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $b7, $f9, $f9, $f9, $99, $80, $20, $b5, $00, $ed, $48, $8b, $4c
@song0ref213:
	.byte $8b, $00, $f9, $f9, $bd
@song0ref218:
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $a3, $4c, $8b, $00, $f9, $9d, $f9, $f9, $f9, $d1, $f9, $ad, $26, $b5, $00, $f9, $e3
	.byte $ff, $17
	.word @song0ref218
	.byte $ff, $0f
	.word @song0ref218
	.byte $99, $38, $b5, $00, $ed, $60, $8b, $64
	.byte $ff, $0b
	.word @song0ref213
	.byte $f9, $d1, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref264:
	.byte $b7
@song0ref265:
	.byte $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $b7, $80, $52, $ed, $44, $99, $42, $99
	.byte $40, $f9, $e3, $56, $b5, $44, $99, $56, $d1, $56, $99, $42, $d1, $50, $99, $3a, $f9, $8f, $00, $ed, $40, $b5, $40, $b5
	.byte $42, $b5, $50, $b5, $4c, $b5, $50, $b5, $38, $f9, $f9, $f9, $97, $00, $b5, $42, $b5, $52, $ed, $56, $99, $42, $99, $40
	.byte $f9, $e3, $44, $b5, $56, $99, $56, $d1, $5a, $99, $52, $d1, $3e, $99, $3a, $f9, $8f, $00, $ed, $40, $b5, $50, $b5, $42
	.byte $b5, $40, $b5, $3a, $b5, $50, $b5, $4a, $f9, $f9, $f9, $97, $00, $b5, $5a, $f9, $f9, $f9, $c1, $5a, $89, $00, $5c, $f9
	.byte $e3, $5a, $f9, $d5, $00, $8b, $f9, $f9, $f9, $d1, $f9, $f9, $f9, $d1, $fd
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
	.byte $ff, $11
	.word @song0ref264
	.byte $ff, $10
	.word @song0ref265
	.byte $ff, $10
	.word @song0ref265
	.byte $ff, $10
	.word @song0ref265
	.byte $fd
	.word @song0ch3loop

; v90 embedded FINAL main gameplay song from uploaded final.s
; Separate one-song FamiTone2 data set named music_data_main.
; Volume lowered in @env0/@env1 so gameplay music is quieter.
; ---------------------------------------------------------------------------

; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Untitled:

.export _music_data_main:=music_data_main

music_data_main:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_main

@instruments:
	.byte $30 ; 00 : Acoustic Grand Piano
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $c7,$70,$00,$00 ; v90 quieter main-song envelope
@env1:
	.byte $c0,$70,$00,$01 ; v90 softened sustain

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@song0ref4:
	.byte $f9, $f9, $f9, $f9, $87, $f9, $f9, $f9, $f9, $87, $f9, $f9, $f9, $f9, $87
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $f9, $f9, $f9, $f9, $87, $bd, $80, $5c, $9d, $5c, $9b, $5c, $bb, $60, $9d, $62, $bb, $66, $9b
@song0ref53:
	.byte $62, $f9, $bd, $00, $bb, $58, $9d, $58, $9b
@song0ref62:
	.byte $58, $bb, $5c, $9d, $60, $bb, $58, $9b
@song0ref70:
	.byte $58, $f9, $bd, $00, $bb, $5c, $9d, $5c, $9b, $5c, $bb, $60, $9d, $62, $bb, $66, $bb, $6a, $8d, $66, $8b, $62, $f9
@song0ref93:
	.byte $00, $bb, $58, $9d, $58, $9b, $58, $bb, $58, $9d, $66, $bb, $5c, $8d, $58, $8b
	.byte $ff, $10
	.word @song0ref70
	.byte $8d, $62, $8b
	.byte $ff, $22
	.word @song0ref53
	.byte $66, $8d, $6a, $8b, $66, $8d, $62, $e9
	.byte $ff, $10
	.word @song0ref93
	.byte $58, $f9, $bd, $00, $f9, $f9, $f9, $f9, $85
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $f9, $f9, $f9, $f9, $87, $f9, $f9, $f9, $f9, $87, $bd, $5c, $9d, $5c, $9b, $5c, $bb, $60, $9d, $62, $bb, $66, $8d, $62
	.byte $8b
	.byte $ff, $38
	.word @song0ref53
	.byte $ff, $10
	.word @song0ref70
	.byte $8d, $62, $8b, $62, $9d, $62, $f9, $9d, $00, $bb, $58, $8d, $58, $9d, $00, $8b
	.byte $ff, $19
	.word @song0ref62
	.byte $66, $8d, $6a, $8b, $66, $8d, $62, $e9, $00, $bb, $58, $9d, $58, $9b, $58, $bb, $58, $9d, $66, $f9, $9d, $58, $db, $58
	.byte $9b, $f9, $f9, $f9, $f9, $87, $00, $f9, $f9, $f9, $f9, $85
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0c
	.word @song0ref4
@song0ref239:
	.byte $83
@song0ref240:
	.byte $f9, $f9, $f9, $a1, $f9, $f9, $f9, $a1, $f9, $f9, $f9, $a1, $f9, $f9, $f9, $a1
@song0ref256:
	.byte $66, $97, $6a, $95, $00, $97, $6a, $95, $6a, $af, $00, $af, $66, $97, $6a, $af, $6a, $95, $70, $97, $6e, $af, $66, $95
	.byte $70, $97, $6e, $f9, $b1, $00, $f9, $cb
	.byte $ff, $13
	.word @song0ref256
@song0ref291:
	.byte $9f, $6e, $9f, $70, $9d, $8d, $6e, $bb, $6a, $89, $66, $f9, $d7, $00, $e1
	.byte $ff, $30
	.word @song0ref240
	.byte $ff, $13
	.word @song0ref256
	.byte $ff, $0f
	.word @song0ref291
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref347:
	.byte $30, $9d, $3e, $9b, $40, $9d, $3e, $9b, $30, $9d, $3e, $9b, $30, $9d, $3e, $9b, $2c, $9d, $3e, $9b, $40, $9d, $3e, $9b
	.byte $2c, $9d, $3e, $9b, $36, $9d, $3e, $9b
	.byte $ff, $10
	.word @song0ref347
@song0ref382:
	.byte $34, $9d, $3a, $9b, $44, $9d, $3a, $9b, $34, $9d, $3a, $9b, $2c, $9d, $3a, $9b
	.byte $ff, $20
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref382
	.byte $ff, $20
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref382
	.byte $ff, $20
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref382
	.byte $ff, $20
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref347
	.byte $ff, $10
	.word @song0ref382
	.byte $24, $9d, $32, $9b, $36, $9d, $24, $9b, $2a, $9d, $30, $9b, $34, $9d, $30, $9b, $30, $9d, $3a, $9b, $42, $9d, $30, $9b
	.byte $3a, $9d, $42, $9b, $48, $9d, $4e, $9b
@song0ref466:
	.byte $2c
@song0ref467:
	.byte $9d, $4a, $9b, $44, $9d, $3a, $9b, $52, $9d, $3a, $9b, $40, $8d, $44, $8d, $4a, $9b, $40
@song0ref485:
	.byte $bb, $4a, $9d, $3a, $9b, $52, $9d, $3a, $9b, $40, $8d, $44, $8d, $48, $9b, $40
@song0ref501:
	.byte $bb, $4e, $9d, $36, $9b, $58, $9d, $36, $9b, $44, $9d, $40
@song0ref513:
	.byte $9b, $40, $bb, $3a, $9d, $30, $9b, $40, $b7, $4b, $48, $bb, $48
	.byte $ff, $11
	.word @song0ref467
	.byte $3a
	.byte $ff, $0f
	.word @song0ref485
	.byte $28, $bb, $4e, $9d, $36, $9b, $58, $9d, $36, $9b, $40, $87, $44, $87, $40, $89, $40, $91, $00, $87, $3a, $9d, $22, $9b
	.byte $3a, $9d, $30, $9b, $40, $b7, $4b, $48, $bb, $3a
	.byte $ff, $11
	.word @song0ref467
	.byte $32
	.byte $ff, $1b
	.word @song0ref485
	.byte $58, $9b, $40, $bb, $3a, $9d, $30, $9b, $40, $b7, $45, $48, $bb, $3a
	.byte $ff, $2b
	.word @song0ref467
@song0ref591:
	.byte $4e, $9d, $44, $9b, $48, $9d, $22, $9b, $3a, $9d, $30, $9b, $48, $b7, $4b, $48, $bb, $48
	.byte $ff, $2d
	.word @song0ref467
	.byte $58
	.byte $ff, $0d
	.word @song0ref513
	.byte $ff, $11
	.word @song0ref467
	.byte $32
	.byte $ff, $19
	.word @song0ref485
	.byte $ff, $0f
	.word @song0ref591
	.byte $4e, $bb, $48
	.byte $ff, $21
	.word @song0ref467
	.byte $28, $bb, $4e, $9d, $36, $9b, $58, $9d, $36, $9b, $58, $9d, $58, $9b, $22, $bb, $3a, $9d, $30, $9b, $48, $b7, $4b, $4e
	.byte $bb
	.byte $ff, $12
	.word @song0ref466
	.byte $32
	.byte $ff, $19
	.word @song0ref485
	.byte $4e, $9d, $44, $9b, $52, $9d, $3a, $9b, $52, $9d, $22, $9b, $4a, $9d, $52, $9b, $3a, $9d, $52, $9b, $2c, $db, $44, $9b
	.byte $4c, $9d, $22, $8d, $22, $8b, $28, $9d, $36, $9b, $52, $db, $52, $9b, $52, $9d, $22, $8d, $22, $8b, $28, $9d, $36, $9b
	.byte $3a, $bb, $00, $9d, $44, $9b, $44, $bb, $36, $bb, $48, $db, $5a, $9b, $3a, $9d, $22, $8d, $22, $8b, $32
@song0ref733:
	.byte $9d, $30, $9b, $48, $db, $4c
@song0ref739:
	.byte $9b, $2c
@song0ref741:
	.byte $9d, $22, $8d, $22, $8b, $28, $9d, $36, $9b, $40, $db, $52, $9b, $4a
@song0ref755:
	.byte $9d, $22, $8d, $22, $8b, $28, $9d, $36, $9b, $4c, $bb, $00, $9d, $2c, $9b, $3a, $bb, $28, $9d, $34, $9b, $22, $f9, $f9
	.byte $81, $44, $db, $3a, $9b, $4c
	.byte $ff, $0d
	.word @song0ref741
	.byte $32
	.byte $ff, $0d
	.word @song0ref755
	.byte $4c, $9b, $2c, $bb, $4e, $bb, $52, $db, $3a, $9b, $52, $9d, $22, $8d, $22, $8b, $40
	.byte $ff, $15
	.word @song0ref733
	.byte $32, $9d, $22, $8d, $22, $8b, $28, $9d, $36, $9b, $44, $bb, $00, $9d, $2c, $9b, $44, $bb, $28, $9d, $34, $9b, $42, $f9
	.byte $f9, $81, $44
	.byte $ff, $11
	.word @song0ref467
	.byte $32
	.byte $ff, $1b
	.word @song0ref485
	.byte $58, $9b, $40, $bb, $3a, $9d, $30, $9b, $48, $b7, $4b, $4e, $bb, $44
	.byte $ff, $2b
	.word @song0ref467
@song0ref863:
	.byte $4e, $9d, $44, $9b, $52, $9d, $22, $9b, $3a, $9d, $30, $9b, $40, $ad, $00, $87, $4b, $4e, $bb, $48
	.byte $ff, $35
	.word @song0ref467
	.byte $48, $bb, $48, $bb
	.byte $ff, $22
	.word @song0ref466
	.byte $28, $bb, $4e, $9d, $36, $9b, $58, $9d, $36, $9b
	.byte $ff, $0d
	.word @song0ref863
	.byte $bb, $4e, $bb
	.byte $ff, $12
	.word @song0ref466
	.byte $32
	.byte $ff, $0f
	.word @song0ref485
	.byte $28
	.byte $ff, $13
	.word @song0ref501
	.byte $48, $bb, $4e, $bb, $48
	.byte $ff, $2b
	.word @song0ref467
	.byte $4e, $9d, $44, $9b, $40, $9d, $22, $9b, $4a, $9d, $52, $9b, $3a, $9d, $52, $9b, $3a, $9d, $52, $9b, $48, $db, $4c
@song0ref951:
	.byte $9b, $44
@song0ref953:
	.byte $9d, $22, $8d, $22, $8b, $28, $9d, $36, $9b, $32, $db, $4a, $9b, $52
	.byte $ff, $0d
	.word @song0ref755
	.byte $3a, $9b, $3a, $bb, $4e, $bb, $5a, $db, $5a, $9b, $3a, $9d, $22, $8d, $22, $8b, $40, $9d, $40, $9b, $2c, $db, $44, $9b
	.byte $3a
	.byte $ff, $0d
	.word @song0ref953
	.byte $32
	.byte $ff, $0d
	.word @song0ref755
	.byte $3a, $9b, $4c, $bb, $36, $9d, $34, $9b, $22, $f9, $f9, $81, $2c, $db, $2c
	.byte $ff, $0d
	.word @song0ref739
	.byte $32, $9b, $52
	.byte $ff, $0f
	.word @song0ref755
	.byte $44, $bb, $36, $bb, $5a, $db, $3a, $9b, $48, $9d, $22, $8d, $22, $8b, $32, $9d, $30, $9b, $2c, $db, $2c
	.byte $ff, $0d
	.word @song0ref951
	.byte $40, $9b, $52, $9d, $22, $8d, $22, $8b, $28, $9d, $36, $9b, $2c, $bb, $00, $9d, $2c, $9b, $44, $bb, $36, $9d, $34, $9b
	.byte $36, $97, $48, $95, $00, $97, $3a, $95, $3a, $e1, $4e, $97, $48, $95, $00, $97, $48, $95, $40, $97, $56, $c7, $00, $97
	.byte $36, $95, $00, $97, $4e, $95, $44
@song0ref1105:
	.byte $c9, $48, $89, $48, $89, $48, $97, $44, $89, $44, $89, $44, $97, $40, $89, $40, $89, $40, $97, $3e, $89, $3e, $89, $3e
	.byte $97, $48, $95, $44, $97, $48, $95, $00, $97, $48, $95, $3a, $e1, $4e, $97, $48
@song0ref1145:
	.byte $95, $00, $97, $52, $95, $58, $97, $4c, $c7, $00, $97, $36, $95, $00, $97, $36, $95, $4e
	.byte $ff, $19
	.word @song0ref1105
	.byte $40, $95, $44, $97, $3a, $95, $00, $97, $48, $95, $48, $e1, $36, $97, $3a, $95, $00, $97, $3a, $95, $40, $97, $3e, $c7
	.byte $00, $97, $4e, $95, $00, $97, $4e, $95, $36
	.byte $ff, $1b
	.word @song0ref1105
	.byte $4e, $97, $48, $95, $00, $97, $52, $95, $3a, $e1, $4e, $97, $3a
	.byte $ff, $11
	.word @song0ref1145
	.byte $36
	.byte $ff, $19
	.word @song0ref1105
	.byte $40, $95, $4e, $97, $3a, $95, $00, $97, $3a, $95, $52, $e1, $4e, $97, $48, $95, $00, $97, $52, $95, $40, $97, $4c, $c7
	.byte $00, $97, $44, $95, $00, $97, $4e, $95, $4e
	.byte $ff, $1b
	.word @song0ref1105
	.byte $36, $97, $3a, $95, $00, $97, $3a, $95, $48, $e1, $36, $97, $3a, $95, $00, $97, $3a, $95, $58, $97, $56, $c7, $00, $97
	.byte $4e, $95, $00, $97, $44, $95, $36
	.byte $ff, $19
	.word @song0ref1105
	.byte $40, $95, $4e, $97, $48, $95, $00, $97, $52, $95, $48, $e1, $4e, $97, $52, $95, $00, $97, $48, $95, $58, $97, $56, $c7
	.byte $00, $97, $36, $95, $00, $97, $36, $95, $4e
	.byte $ff, $1b
	.word @song0ref1105
	.byte $36, $97, $48, $95, $00, $97, $52, $95, $52, $e1, $4e, $97, $3a, $95, $00, $97, $3a, $95, $58, $97, $4c, $c7, $00, $97
	.byte $4e, $95, $00, $97, $36, $95, $4e
	.byte $ff, $19
	.word @song0ref1105
	.byte $40, $95, $00, $f9, $f9, $f9, $9f
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $0c
	.word @song0ref240
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $f9, $f9, $f9, $f9, $87, $f9, $f9, $f9, $a5, $80, $48, $9b, $4e, $9d, $56, $9b, $48, $db, $56, $8d, $58, $8b, $5c, $db
	.byte $58, $8d, $5c, $8b, $60, $a7, $5c, $a5, $58, $a7, $5c, $f9, $9f, $60, $8d, $5c, $8b, $58, $9d, $56, $9b, $58, $9d, $56
	.byte $9b, $52, $9d, $56, $9b, $56, $8d, $58, $8d, $00, $8d, $56, $ab, $52, $9b, $56, $a7, $52, $a5, $4e, $a7, $44, $bb, $48
	.byte $f9, $9f, $4e, $9b, $4c, $f9, $9f, $4e, $9b, $4c, $9d, $58, $9b, $56, $f9, $dd, $58, $9b, $5c, $f9, $bd, $00, $9d, $66
	.byte $8d, $6e, $8b, $78, $8d, $6e, $8d, $66, $8d, $60, $8b, $70, $8d, $6e, $8d, $66, $8d, $5c, $8b, $6a, $8d, $66, $8d, $64
	.byte $8d, $60, $8b, $5c, $f9, $9f, $5c, $8d, $60, $8b, $52, $db, $52, $8d, $56, $8b, $5c, $9d, $60, $9b, $64, $9d, $66, $9b
	.byte $64, $87, $66, $87, $64, $89, $60, $9b, $64, $9d, $66, $9b, $64, $9d, $78, $9b, $74, $9d, $70, $d9, $70, $9d, $74, $9b
	.byte $6e, $bb, $66, $9d, $60, $d9, $6e, $9d, $70, $9b, $6e, $bb, $66, $9d, $5c, $d9, $6e, $9d, $70, $9b, $6e, $bb, $66, $9d
	.byte $74, $d9, $70, $bb, $6e, $f9, $bd, $00, $bb, $44, $9d, $48, $9b, $4a, $9d, $4e, $9b, $52, $9d, $54, $9b, $58, $9d, $5c
	.byte $9b, $60, $9d, $62, $9b, $66, $9d, $6a, $9b, $6c, $9d, $70, $9b, $6c, $87, $70, $87, $6c, $89, $66, $9b, $74, $f9, $f9
	.byte $81, $00, $f9, $f9, $81
	.byte $ff, $0f
	.word @song0ref4
	.byte $44, $f9, $b9, $49, $4a, $bb, $40, $f9, $bd, $58, $9d, $60, $9b, $4e, $f9, $00, $bb, $6a, $bb, $66, $f9, $f9, $81, $44
	.byte $f9, $dd, $4a, $9b, $40, $f9, $bd, $58, $9d, $60, $9b, $66, $f9, $dd, $52, $9b, $58, $f9, $f9, $81, $00, $f9, $f9, $f9
	.byte $f9, $85
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $5c, $f9, $bd, $5c, $9d, $60, $9b, $62, $db, $62, $9b, $66, $a7, $62, $a5, $60, $a7, $58, $f9, $bd, $58, $9d, $5c, $9b
	.byte $52, $f9, $52, $9d, $56, $9b, $56, $9d, $58, $97, $54, $81, $5c, $f9, $bd, $5c, $9d, $60, $9b, $62, $f9, $66, $a7, $66
	.byte $a5, $62, $a7, $66, $bb, $66, $bb, $66, $bb, $66, $bb, $66, $f9, $f9, $81, $00, $f9, $f9, $f9, $f9, $85
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0c
	.word @song0ref4
	.byte $ff, $11
	.word @song0ref239
	.byte $ff, $10
	.word @song0ref240
@song0ref1803:
	.byte $56, $97, $58, $95, $00, $97, $58, $95, $58, $e1, $56, $97, $58, $95, $00, $97, $58, $95, $60, $97, $5c, $c7, $00, $97
	.byte $56, $95, $00, $97, $56, $95, $4e, $c9, $60, $89, $60, $89, $60, $97, $5c, $89, $5c, $89, $5c, $97, $58, $89, $58, $89
	.byte $58, $97, $56, $89, $56, $89, $56, $97, $00, $95
	.byte $ff, $1e
	.word @song0ref1803
	.byte $56, $c9, $56, $89, $56, $89, $56, $97, $52, $89, $52, $89, $52, $97, $4e, $89, $4e, $89, $4e, $97, $4c, $89, $4c, $89
	.byte $4c, $97, $4e, $95, $00, $f9, $f9, $f9, $9f
	.byte $ff, $0c
	.word @song0ref240
@song0ref1900:
	.byte $22, $97, $22, $95, $22, $97, $22, $95, $3a, $c9, $48, $95, $22, $97, $22, $95, $22, $97, $22, $95, $4e, $97, $3e, $c7
	.byte $22, $97, $22, $95, $22, $97, $22, $95, $36
	.byte $ff, $1b
	.word @song0ref1105
	.byte $ff, $14
	.word @song0ref1900
	.byte $40, $97, $56, $c7, $22, $97, $22, $95, $22, $97, $22, $95, $36
	.byte $ff, $19
	.word @song0ref1105
	.byte $40
@song0ref1956:
	.byte $95, $36
@song0ref1958:
	.byte $c9, $3e, $c7, $40, $c9, $3e, $c7, $3a, $97, $36, $95, $34, $97, $2c, $95, $34
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
@song0ref1981:
	.byte $c9, $3e, $c7, $40, $c9, $44, $c7, $40, $97, $3e, $95, $3a, $97, $3e
	.byte $ff, $12
	.word @song0ref1956
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
	.byte $ff, $0e
	.word @song0ref1981
	.byte $ff, $12
	.word @song0ref1956
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
	.byte $ff, $0e
	.word @song0ref1981
	.byte $ff, $12
	.word @song0ref1956
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
	.byte $ff, $0e
	.word @song0ref1981
	.byte $ff, $12
	.word @song0ref1956
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
	.byte $ff, $0e
	.word @song0ref1981
	.byte $ff, $12
	.word @song0ref1956
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
	.byte $ff, $0e
	.word @song0ref1981
	.byte $ff, $12
	.word @song0ref1956
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
	.byte $ff, $0e
	.word @song0ref1981
	.byte $ff, $12
	.word @song0ref1956
	.byte $ff, $0f
	.word @song0ref1958
	.byte $30
	.byte $ff, $10
	.word @song0ref1958
	.byte $c9, $3e, $c7, $40, $c9, $00, $f9, $b1, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $f9, $f9, $f9, $f9, $87, $f9, $f9, $f9, $f9, $87, $80, $5c, $9d, $3e, $9b, $3e, $9d, $32, $9b, $36
@song0ref2154:
	.byte $9d, $3e, $9b, $3e, $9d, $32, $9b, $3e
@song0ref2162:
	.byte $9d, $3e, $9b, $3e
@song0ref2166:
	.byte $9d, $3e, $9b, $3e, $9d, $3e, $9b, $3e, $9d, $3e, $9b, $32
	.byte $ff, $0d
	.word @song0ref2162
	.byte $32, $9b, $3e, $9d, $3e, $9b, $3e, $9d, $3e, $9b, $32, $bb, $00, $bb, $5c
	.byte $ff, $10
	.word @song0ref2162
	.byte $9d, $3e, $9b, $3e, $9d, $32, $9b, $36, $9d, $00, $9b, $3e, $9d, $32, $9b, $32
	.byte $ff, $0d
	.word @song0ref2154
	.byte $32, $9b, $5c, $ad, $36, $8b, $36, $9d, $44, $9b, $5c, $ad, $36, $8b, $36, $9d, $36, $9b, $32, $bb, $3e, $9d, $3e, $9b
	.byte $3e, $9d, $3e, $9b, $3e, $9d, $32, $9b, $32
	.byte $ff, $10
	.word @song0ref2162
	.byte $9d, $3e, $9b, $3e, $9d, $3e, $9b, $5c, $bb, $3e, $9d, $3e, $9b, $4a, $9d, $4a, $9b, $4a, $9d, $48, $9b, $4a, $9d, $48
	.byte $9b, $36, $bb, $5c, $bb, $3e, $9d, $3e, $9b, $36, $9d, $36, $8d, $36, $8b, $32, $9d, $30, $9b, $32, $bb, $3e, $9d, $3e
	.byte $9b, $36, $9d, $32, $9b, $5c, $9d, $5c, $9b, $5c
	.byte $ff, $0c
	.word @song0ref2166
	.byte $bb, $32, $bb
@song0ref2318:
	.byte $36, $9d, $3e, $9b, $4a, $87, $48, $87, $32, $89, $30, $9b, $4a, $87, $48, $87, $32, $89, $30
@song0ref2337:
	.byte $9b, $32, $9d, $3e, $9b, $3e, $9d, $3e
@song0ref2345:
	.byte $9b, $36, $9d, $36, $8d, $36, $8b, $5c, $9d, $5c, $9b, $32, $9d, $3e, $9b, $3e, $9d, $32, $9b, $36, $9d, $32, $9b, $5c
	.byte $9d, $5c, $9b, $5c
	.byte $ff, $0c
	.word @song0ref2166
	.byte $9d, $32, $9b, $5c, $9d, $3e, $9b
	.byte $ff, $0c
	.word @song0ref2318
	.byte $36, $9d, $5c, $9b, $5c, $bb, $3e, $9d, $32
	.byte $ff, $11
	.word @song0ref2345
	.byte $3e, $9b, $36, $9d, $32, $9b, $5c, $9d, $5c, $9b, $32, $9d, $3e, $9b, $3e, $9d, $3e, $9b, $36, $9d, $3e, $9b, $5c, $bb
	.byte $32, $bb, $36, $9d, $44, $87, $44, $83, $01, $45, $00, $83, $48, $9d, $48, $9b, $4a, $9d, $4a
	.byte $ff, $0f
	.word @song0ref2337
	.byte $32, $9d, $32, $9b, $32, $9d, $3e, $9b, $3e, $9d, $32, $9b, $3e, $9d, $5c, $9b, $5c, $9d, $32, $9b, $32
	.byte $ff, $0c
	.word @song0ref2166
	.byte $9d, $32, $9b, $5c, $af, $00, $f9, $f9, $e7, $f9, $f9, $f9, $a1, $5c, $af, $00, $f9, $f9, $e7, $f9, $b5, $32, $85, $32
	.byte $85, $32, $85, $5c, $97, $32, $85, $32, $85, $32, $85, $36, $97, $32, $85, $32, $85, $32, $85, $36, $97, $32, $85, $32
	.byte $85, $32, $85, $36, $97, $32, $95, $32, $97
@song0ref2525:
	.byte $3e, $95, $3e
@song0ref2528:
	.byte $97, $3e, $95, $3e, $97, $3e, $95, $3e, $97, $3e, $95, $32, $97, $3e, $95, $3e, $97, $32, $89, $32, $89, $36, $97, $32
	.byte $95, $32, $af, $32, $97, $3e, $95
@song0ref2559:
	.byte $3e, $97, $32, $95, $36, $97, $3e, $95, $3e, $97, $3e, $95, $36, $97, $32, $95, $36, $97, $5c, $95, $36, $97, $32, $95
	.byte $36, $97, $5c, $95, $32, $97, $46, $95, $46, $97, $32, $95, $3e
@song0ref2596:
	.byte $97, $3e, $95, $3e, $97, $32, $95, $3e, $97, $3e, $95, $3e, $97, $32
@song0ref2610:
	.byte $89, $32, $89, $3e, $97, $36, $89, $36, $89, $36, $97, $5c, $95, $5c, $97, $3e, $95, $3e, $97, $3e, $95, $36, $af, $3e
	.byte $97, $3e, $95, $36, $97, $36, $89, $36, $89, $36, $97, $36, $95, $44, $8b, $44, $89, $32, $89, $32, $89, $36, $97, $5c
	.byte $95, $32, $af, $3e, $97, $3e, $95, $36
	.byte $ff, $11
	.word @song0ref2528
	.byte $3e, $95, $5c, $af, $32, $af, $3e, $97, $32, $95, $3e, $97, $3e, $95, $3e, $97, $3e, $95, $36, $97, $3e
@song0ref2690:
	.byte $95, $36, $97, $3e, $95, $36, $97, $3e, $95, $36, $97, $5c, $95, $5c, $af, $3e, $97, $32, $95, $3e, $97, $3e, $95, $3e
	.byte $97, $32, $95, $32, $97, $3e, $95, $3e, $97, $3e
	.byte $ff, $0e
	.word @song0ref2610
	.byte $af, $3e, $97, $3e, $95, $32, $af, $3e, $97, $32, $95, $36, $97, $36, $89, $36, $89, $44, $8b, $44, $89, $48, $89, $48
	.byte $89, $4a, $8b, $4a, $89, $4a, $89, $4a, $89, $4e, $8b, $4e, $89, $40, $89, $40, $89, $32, $97, $46, $95, $46, $97, $46
	.byte $95, $36
	.byte $ff, $0d
	.word @song0ref2596
	.byte $3e, $89, $32, $89, $36, $97, $5c, $95, $32, $af, $32, $af, $3e, $97, $3e, $95, $36, $af, $3e, $97, $3e, $95, $36, $af
	.byte $3e, $97, $32, $95, $36, $97, $5c, $95, $5c, $af, $5c
	.byte $ff, $0d
	.word @song0ref2596
	.byte $ff, $0c
	.word @song0ref2525
	.byte $36, $89, $36, $89, $36, $97, $32, $95, $5c, $af
	.byte $ff, $0c
	.word @song0ref2559
	.byte $5c, $97, $36, $89, $36, $89, $36, $97, $36, $89, $36, $89, $36, $8b, $36, $89, $36, $89, $36, $89, $32, $af, $32, $af
	.byte $36, $af
@song0ref2860:
	.byte $32, $af, $36, $af, $3e, $97, $32, $95, $36, $97, $32, $95, $3e, $af, $3e, $af, $3e, $97, $32, $95, $3e, $97, $32, $95
	.byte $32, $af, $3e, $af, $32
@song0ref2889:
	.byte $97, $32, $85, $32, $85, $32, $85, $36, $af, $3e, $97, $32, $85, $32, $85, $32, $85, $5c, $af, $5c, $af, $36, $af, $3e
@song0ref2913:
	.byte $97, $32, $95, $3e, $af, $32, $af, $3e, $af, $3e, $97, $32, $95, $36, $af, $3e, $af, $36, $af, $32, $97, $32, $95, $36
	.byte $af, $36, $a3, $36, $89, $36, $97, $44, $95, $48, $97, $48, $89, $48, $89, $4a, $97, $4a, $95, $32
@song0ref2957:
	.byte $af, $3e
@song0ref2959:
	.byte $af, $3e, $97, $32, $95, $36
@song0ref2965:
	.byte $af
@song0ref2966:
	.byte $3e, $97, $32, $95, $3e, $97, $32, $95, $3e, $97, $32, $95, $36, $af, $5c, $af, $3e, $af, $3e, $97, $32, $95, $36, $97
	.byte $32, $95
	.byte $ff, $0c
	.word @song0ref2966
	.byte $3e, $af, $5c, $af, $3e
	.byte $ff, $0d
	.word @song0ref2965
	.byte $3e, $97, $32, $95, $3e, $97, $32, $85, $32, $85, $32, $85, $36, $af, $5c
@song0ref3018:
	.byte $af, $3e, $af, $3e, $97, $32, $95, $3e, $af, $32, $97, $32, $95, $36, $97, $36, $95, $3e, $97, $32, $95, $36, $97, $32
	.byte $89, $30, $89, $5c
	.byte $ff, $16
	.word @song0ref2957
	.byte $97, $32, $89, $30, $89
	.byte $ff, $0d
	.word @song0ref2860
	.byte $97, $32, $95, $36, $97, $32, $95, $3e, $97, $32, $95, $5c, $97, $32, $89, $30, $89, $32, $af, $3e, $af, $3e, $97, $32
	.byte $95, $3e, $af, $3e, $97, $32, $95, $3e, $97, $32, $89, $30, $89, $3e, $af, $5c, $97, $32, $89, $30, $89, $32, $af, $36
	.byte $af, $32, $97, $32, $95, $36, $af, $32, $97, $32, $95, $5c, $a3, $36, $89, $36, $97, $36, $95, $4a, $87, $4a, $85, $4a
	.byte $85, $4a, $85, $4e, $85, $4e, $85, $5c, $af, $36
	.byte $ff, $0c
	.word @song0ref2959
	.byte $af, $32
	.byte $ff, $0d
	.word @song0ref2913
	.byte $3e, $af, $3e, $97, $32
	.byte $ff, $0d
	.word @song0ref2690
	.byte $32
	.byte $ff, $0d
	.word @song0ref3018
	.byte $3e, $af, $32, $97, $32, $95, $3e, $af, $5c, $af, $36, $af, $32, $97, $32, $95, $3e, $af, $3e
	.byte $ff, $11
	.word @song0ref2889
	.byte $36, $af
@song0ref3183:
	.byte $32
@song0ref3184:
	.byte $8b, $30, $89, $32, $89, $30, $89, $32, $8b, $30, $89, $32, $89, $30, $89
	.byte $ff, $10
	.word @song0ref3183
	.byte $ff, $10
	.word @song0ref3183
	.byte $32, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $ff, $10
	.word @song0ref3183
@song0ref3220:
	.byte $3e
@song0ref3221:
	.byte $8b, $30, $89, $32, $89, $30, $89, $3e, $8b, $30, $89, $32, $89, $30, $89
	.byte $ff, $10
	.word @song0ref3220
	.byte $ff, $10
	.word @song0ref3183
	.byte $ff, $10
	.word @song0ref3183
	.byte $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $ff, $10
	.word @song0ref3183
	.byte $32
	.byte $ff, $0f
	.word @song0ref3221
	.byte $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $60
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36
	.byte $ff, $0f
	.word @song0ref3184
@song0ref3268:
	.byte $36
@song0ref3269:
	.byte $8b, $30, $89, $32, $89, $30, $89, $5c, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3221
	.byte $3e
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32
	.byte $ff, $0f
	.word @song0ref3221
	.byte $32
	.byte $ff, $10
	.word @song0ref3269
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36
	.byte $ff, $0f
	.word @song0ref3221
	.byte $ff, $10
	.word @song0ref3183
	.byte $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $3e
	.byte $ff, $0f
	.word @song0ref3184
	.byte $3e
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36
	.byte $ff, $0f
	.word @song0ref3221
	.byte $3e
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32, $8b, $30, $89, $32, $89, $30, $89
	.byte $ff, $10
	.word @song0ref3268
	.byte $5c, $8b, $30, $89, $32, $89, $30, $89, $36, $8b, $30, $89, $36, $85, $37, $31, $36, $85, $36
@song0ref3360:
	.byte $8b, $30, $89, $36, $89, $30, $89, $32, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3221
	.byte $32, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $ff, $10
	.word @song0ref3183
	.byte $ff, $10
	.word @song0ref3183
	.byte $32, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32
	.byte $ff, $0f
	.word @song0ref3221
	.byte $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32, $8b, $30, $89, $32, $89, $30, $89
	.byte $ff, $11
	.word @song0ref3268
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36, $8b, $30, $89, $32, $89, $30, $89, $48, $8b, $30, $89, $32, $89, $30, $89, $4a
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36
	.byte $ff, $0f
	.word @song0ref3221
	.byte $32, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3221
	.byte $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $5c
	.byte $ff, $0f
	.word @song0ref3184
	.byte $3e
	.byte $ff, $0f
	.word @song0ref3184
@song0ref3507:
	.byte $3e
@song0ref3508:
	.byte $8b, $30, $89, $32, $89, $30, $89, $36, $8b, $30, $89, $32, $89, $30, $89, $36
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32
	.byte $ff, $0f
	.word @song0ref3221
	.byte $ff, $10
	.word @song0ref3183
	.byte $3e
	.byte $ff, $0f
	.word @song0ref3184
	.byte $36
	.byte $ff, $10
	.word @song0ref3508
	.byte $8b, $30, $89, $32, $89, $36, $89, $36, $8b, $36, $89, $32, $89, $30, $89, $32, $8b, $36, $89, $32, $89, $30, $89, $36
	.byte $8b, $30, $89, $36, $89, $30, $89, $32, $8b, $36, $89, $32, $89, $30, $89, $32
	.byte $ff, $0f
	.word @song0ref3360
	.byte $ff, $10
	.word @song0ref3183
	.byte $32
	.byte $ff, $0f
	.word @song0ref3221
	.byte $32
	.byte $ff, $0f
	.word @song0ref3508
	.byte $ff, $10
	.word @song0ref3183
	.byte $32
	.byte $ff, $0f
	.word @song0ref3508
	.byte $32
	.byte $ff, $0f
	.word @song0ref3221
	.byte $3e
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32
	.byte $ff, $0f
	.word @song0ref3508
	.byte $32
	.byte $ff, $0f
	.word @song0ref3508
	.byte $ff, $11
	.word @song0ref3507
	.byte $ff, $0f
	.word @song0ref3184
	.byte $32
	.byte $ff, $10
	.word @song0ref3508
	.byte $ff, $0f
	.word @song0ref3184
	.byte $ff, $10
	.word @song0ref3268
	.byte $32, $8b, $30, $89, $32, $89, $30, $89, $00, $f9, $cb, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $ff, $0f
	.word @song0ref4
	.byte $f9, $f9
	.byte $ff, $11
	.word @song0ref239
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $ff, $10
	.word @song0ref240
	.byte $fd
	.word @song0ch4loop
